version: '3.8'

services:
  php-app:
    # image: php
    # container_name: php-app
    # ports:
    #   - "8088:8080"
    volumes:
      - ./src:/var/www
    # run: docker-php-ext-install mysqli
    # command: php -S 0.0.0.0:8080 -t /var/www

    build: .
    ports:
      - "8088:8080"
    # links:
    #   - mysql-db

  mysql-db:
    image: mysql
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: films
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql-data:/var/lib/mysql

# volumes:
#   mysql-data:
